name: AWS VPC Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::592964950410:role/GitHubActions-AWS-VPC
          aws-region: us-east-1

      - name: Check AWS connection
        run: aws sts get-caller-identity
        
      - name: Run AWS VPC script
        run: |
          chmod +x aws_script.sh
          ./aws_script.sh
